ifBuild Signed APK (Stable)

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test secrets
        run: |
         if [ -z "${{ secrets.KEYSTORE_PASSWORD }}" ]; then
          echo"❌ KEYSTORE_PASSWORD is EMPTY"
         else
          echo "✅ KEYSTORE_PASSWORD is SET"
         fi
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Briefcase
        run: |
          python -m pip install --upgrade pip
          pip install briefcase

      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks
      
      - name: List keystore aliases
        run: |
          keytool -list -keystore keystore.jks -storepass ${{ secrets.KEYSTORE_PASSWORD }}    

      - name: Create Android project
        run: |
          briefcase create android

      - name: Build Debug APK
        run: |
          briefcase build android

      - name: Sign APK manually
        run: |
          APK=build/android/app/build/outputs/apk/debug/app-debug.apk
          jarsigner \
            -keystore keystore.jks \
            -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
            -keypass ${{ secrets.KEY_PASSWORD }} \
            $APK \
            $calculatorkey

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: signed-apk
          path: build/android/app/build/outputs/apk/debug/app-debug.apk
